### PR TITLE
Dev authentication

### PR DESCRIPTION
**Pull request by Looby72**
# Implementation of authentication for the user API route #20
- user only can access or change date from theirselves except they're admins
- user API route now supports multiple HTTP status codes
- login and authentication process now done with cookies (inside the cookies, the JWT is stored) #42
- some changes in exercise API route, had to change some status codes and some minor bug fixes
- user and exercise routes changed according to the new database models

## Things that have to be done:
- resending the auth-cookie to the client with every HTTP request (at the moment the cookie is only valid one hour after the login process)
- documentation for the user route (done by @SamiFy)

### CODE REVIEW

**Comment by mlinke-ai** [comment]
Returning all exercises with "exercise_id=0" is not feasible for us. It would simply return the exercise with index 0. I would recommend we use -1 for this purpose.

On the other hand returning all exercises when there are hundreds or thousands would overwhelm the API. We could use paging. When "exercise_id=-1" we look for two additional optional arguments "exercise_start" and "exercise_amount". If they are given we return the amount "exercise_amount" of exercises, starting from the index "exercise_start". The next page starts at "exercise_start + exercise_amount". If "exercise_amount" is not given we can use a default value. If both arguments are not given we return an error code.

**Comment by Looby72** [comment]
I think our database system starts with `id=1` for every pimary key in every table. I don't know why, but when I query the system for Attrbibute exercise_id like this:
```Python
query = db_engine.select(exercise_table).select_from(exercise_table)
query = query.where(exercise_table.c.exercise_id == args["exercise_id"])
```
and set `args["exercise_id"] = 0`, then all items will be selected. It's the same with the user table.

The paging is a good idea. I will look into it.

**Comment by mlinke-ai** [comment]
The databases starting at index 1 is somehow correct but quite strange. The documentation says nothing about this.

However, I have an issue where I get always all rows returned, regardless of filter/argument I apply (issue #45).

**Comment by Looby72** [comment]
I added a new Constant in the config, with a maximum of returned items. If the client sends a GET request with id <1 the id will just be ignored for now. If we need further improvements on that in the future, I would implement that later.

**Pull request merged**
