### PR TITLE
Dev jwt auth

### PR DESCRIPTION
**Pull request by Looby72**
# First step of implementing the JWT authentication (#20)

- reworked the exercise API route to make all methods more HTTP standardized -> with status codes and GET arguments in URL
- documented all methods of exercise API route
- implemented first simple authentication in exercise API route (every logged in user has access to all exercise methods)
- made GET method of user API route HTTP standardized -> with GET arguments in URL
- changed access commands from user API route (GET Method), such that it works with URL arguments

### CODE REVIEW

**Review by mlinke-ai — COMMENTED** [review]
Would marking the "Authorization" argument as required be a good idea?

**Comment by Looby72** [comment]
This would do the same as it does now. Insted of a HTTP status 401 (Unauthorized) we would get a 400 (Bad Request) and the following JSON response:
```JSON
{
    "message": {
        "Authorization": "no JSON Web Token was sent"
    }
}
```
as it is now we would get:

```JSON
{
    "message": "Login required."
}
```
I don't know what is better.

**Comment by mlinke-ai** [comment]
I would propose we set "Authorization" as required. It is only reasonable that a missing header causes a 400 error. On the other hand I assume error 401 is used when a request with a user token tries to retrieve data from an endpoint where an admin token is required.

**Comment by Looby72** [comment]
If a client sends valid data to authenticate, but the server refuses action e.g. because the user doesn't have the necessary permissions, then a 403 should be sent. (see [Wikipedia](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_client_errors))

**Review by mlinke-ai — APPROVED** [review]
Nice :+1:

**Pull request merged**
