### PR TITLE
Dev pagination

### LINKED ISSUE #123: GET number of all users/exercises/solutions
I need the number of all users/exercises/ solutions (with key=value) for displaying them and for calculating user statistics for each user. Please help!

### PR DESCRIPTION
**Pull request by mlinke-ai**
The changes in this PR are only exemplary to the `ExerciseResource`. In the future these changes should be made to all API endpoints with `GET` methods.

The purpose of these changes is to introduce proper pagination and to return some meta data with the response.

### Changes to the request

The `exercise_offset` argument is now called `exercise_page`. The default value for this argument is `1`. When setting the value manually it has to be an integer and must be greater than `0`. However setting this value by hand should not be necessary because of `next_url` and `prev_url`.

### Changes to the response

The response has a completely new structure:

```json
{
    "data": [...],
    "meta": {
        "next_page": ...,
        "next_url": ...,
        "page_size": ...,
        "pages": ...,
        "prev_page": ...,
        "prev_url": ...,
        "total": ...
    }
}
```

| Field | Description |
|:--|:--|
| `"data"` | A list of the elements returned by the query ordered by `exercise_id`. |
| `"next_page"` | The index of the next page. If there is no next page this value will be `null`. |
| `"next_url"` | The URL to request the next page. If there is no next page this value will be `null`. |
| `"page_size"` | The number of elements in the current page. |
| `"pages"` | The number of pages. |
| `"prev_page"` | The index of the previous page. If the is no previous page this value will be `null`. |
| `"prev_url"` | The URL to request the previous page. If there is no previous page this value will be `null`. |
| `"total"` | The total number of elements which match the query. Basically the sum of all page sizes. |

The field `"total"` should be sufficient to resolve #123 .

### Miscellaneous changes

- `ExerciseModel` has a `to_json()` function. This is a convenient way to transform an exercise instance into a dictionary
- `exercise_type` and `exercise_language` get returned as both integer and string as the API endpoints require integers in requests but the front end also needs the strings for displaying

### CODE REVIEW

**Comment by Looby72** [comment]
Looks Great!
Returning the items as a list rather than a dict is a good idea.

A few comments from my side:
- The `exercise_content` and `exercise_solution` attributes should be returned as raw JSON, not as String. For that I used the `json.loads()` method.
- Is there a reason to use the `make_response` instead of the `utilsmakeResponseNewCookie` in exercise/get?
- Why did you removed the authentication part in exercise/get, just for testing purposes?
- For the `exercise_content` attribut I wrote a method `utils.prepareExerciseContent` for randomizing the parsons puzzle content. That should somhow be connected again

Do you need some help from my side? (e.g. adjusting UnitTests or rewriting docs)

**Comment by Looby72** [comment]
And I found a print statement somwere, printing the `exercise_page` attribute. This should also be removed before merging.

**Comment by mlinke-ai** [comment]
It is only a work in progress so here and there will be some print statements. That's also why I commented out authorization and the return statement.

Good point about the `json.loads()`. I will add that.

Yes, rewriting tests and documentation would help me very much. Thanks for that.

**Comment by just-Jana** [comment]
Looks good and well thought of. Thank you!
How do I get access to the meta data then? Will the URL look the same?

**Comment by Looby72** [comment]
I don't know how to access json in JS exactly, but it should be something like.
```JavaScript
//the JSON data is stored in response
number = response.meta.total;
```

**Comment by Looby72** [comment]
while creating the Unit tests for the exercise/GET I noticed some unexpected results:
- when setting `exercise_details` to true it still shows all attributes
- querying by `exercise_solution` and `exercise_content` does not work (I think because we try to pass JSON data through the URL there)

**Comment by mlinke-ai** [comment]
I think you meant when you set `exercise_details` to `false` you still get all attributes. This is an effect I observed by myself already and it has something to do with how the parsing of the arguments is done.

In Python when converting between types one calls the respective function of that type (`int()` for integers, `str()` for strings etc.). That's also what we did in the argument definition of the request argument parser. There we have written something like `type=boot` which means "when you get this argument, parse the value with the `bool()` casting function". However initially every argument value is a string. And every string, except for the empty string, will be parsed as `true`.

So as long as we don't have a fix for this, either the respective test has to fail all the time or we simply don't send the `exercise_details` argument.

For the second problem: querying by `exercise_solution` or `exercise_content` is useless. I added those just to make the API complete. If we really wanted to allow searching with this arguments we would need something like a full text search. Maybe even a custom FTS as we are using JSON strings. We could remove those arguments or raise an error when they are used. I have no clear vision about this.

**Pull request merged**
