### PR TITLE
Cookie Acception Banner

### PR DESCRIPTION
**Pull request by aschadli**
I created a cookie acceptance banner that appears every time you load the web app.
It stays in the center of the page and blurs the background until you click OK.
Additionally I added the footer below the home route as the footer doesn't seem to work properly on some other pages (don't know why) but is only really needed on the home route.

### CODE REVIEW

**Comment by Looby72** [comment]
somehow the accept button and the text is missplaced on my screen. (see screenshot)
image

It would also be nice if we could manage that we don't have to accept it every time. Maybe you could create an entry in the local storage of the browser for that. It is possible with JS.

**Comment by aschadli** [comment]
Weird how this is displayed on your screen. I'll take a look again.
Also with the local storage. Is that actually a cookie or something else?

**Comment by Looby72** [comment]
almost like a cookie, with the difference that the data is not sent to the server. It will also survive closing the browser. For usage you can see [this](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage?retiredLocale=de).

**Comment by aschadli** [comment]
Thanks for the tip!
I have now implemented that a flag is created in local storage. I also revised the layout again.

**Comment by Looby72** [comment]
Nice! 👍 The footer also looks great! Maybe we manage to implement it on every page in the future.

**Review by Looby72 — APPROVED** [review]

**Comment by Pymon** [comment]
Looks great!
But I would like to remind you that we agreed upon using the pre-built components of smui whenever possible. There is already a "mandatory dialog" in the library that perfectly fits the needs of a cookie popup: https://sveltematerialui.com/demo/dialog/ (Can often save some time). But I think your handcrafted dialog still looks great and fits in well. I actually like your blur effect better than the one provided by smui. 
I don't know if this is a bug or a feature, but the navbar is the only component not being blurred out. This is because the navbar has a z-index of 999. If you want to fix this, you can set the blur's z-index in css to something higher and the banner's to greater than something higher.
The footer looks really nice too, but maybe could display the "Zurück nach oben" message only if the user has scrolled down. Also it should be in English, like the rest of the website lol.

**Review by Pymon — APPROVED** [review]
Ready to be merged 👍

**Comment by aschadli** [comment]
Thanks for the hints @Pymon !
I think I overlooked the dialog component and tryed the banner component. But I had some issues with that and was disappointed and therefore made it myself. I will leave it like that, because I think my blur is actually better too.
That the navbar is not blured is an ignored bug. I will try your explanation to fix this.
And I will change the text in the footer to English lol.

**Pull request merged**
