### PR TITLE
Made various graphical enhancements and small bug fixes

### PR DESCRIPTION
**Pull request by Pymon**
- extended Login component
- optimized Navbar config
- updated ReadMe
- made graphical changes
- fixed various small bugs
- TODO: fix media errors

### CODE REVIEW

**Comment by Pymon** [comment]
Currently only works properly on the backend server, media imports in frontend are broken now xD

**Comment by Looby72** [comment]
looks really nice 👍🏻

**Comment by scrap111** [comment]
Why did you change the colors to green again? Thought I changed them to the colors of the logo 🤔

**Review by scrap111 — APPROVED** [review]
LGTM👍

**Comment by Pymon** [comment]
@scrap111 I think this kind of red is too aggressive for a primary color. What made me change it was the fact, that whenever you click in a text field it becomes red. This color typically has the task to warn users or draw attention and could confuse some users or make it seem that something is wrong. 
The current color scheme is definitely not the final solution, but something we can work with for now.

**Pull request merged**
